import Header from "../components/myHeader/Header";
import Footer from "../components/myFooter/Footer";
import AnimationScreen from "../components/myAnimationScreen/AnimationScreen";

const Home = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <div className="flex flex-row justify-between items px-40 items-center flex-grow">
        <p className="text-base md:text-lg leading-relaxed max-w-2xl">
          This website uses Shapley value algorithm,
          The Shapley value is a solution concept in cooperative game theory. It
          was named in honor of Lloyd Shapley, who introduced it in 1951 and won
          the Nobel Memorial Prize in Economic Sciences for it in 2012. To
          each cooperative game it assigns a unique distribution (among the
          players) of a total surplus generated by the coalition of all players.
          The Shapley value is characterized by a collection of desirable
          properties.
        </p>
        <AnimationScreen />
      </div>
      <Footer />
    </div>
  );
};

export default Home;
